// <auto-generated />
using System;
using CatalogService.DAL.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CatalogService.DAL.Migrations
{
    [DbContext(typeof(CatalogDbContext))]
    [Migration("20251118155626_RemoveSize")]
    partial class RemoveSize
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CatalogService.Domain.Entities.Bouquet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("MainPhotoUrl")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric(10,2)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Bouquets", (string)null);
                });

            modelBuilder.Entity("CatalogService.Domain.Entities.BouquetEvent", b =>
                {
                    b.Property<Guid>("BouquetId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid");

                    b.HasKey("BouquetId", "EventId");

                    b.HasIndex("EventId");

                    b.ToTable("BouquetEvents", (string)null);
                });

            modelBuilder.Entity("CatalogService.Domain.Entities.BouquetFlower", b =>
                {
                    b.Property<Guid>("BouquetId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("FlowerId")
                        .HasColumnType("uuid");

                    b.Property<int>("Quantity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.HasKey("BouquetId", "FlowerId");

                    b.HasIndex("FlowerId");

                    b.ToTable("BouquetFlowers", null, t =>
                        {
                            t.HasCheckConstraint("CK_BouquetFlower_Quantity_Positive", "\"Quantity\" > 0");
                        });
                });

            modelBuilder.Entity("CatalogService.Domain.Entities.BouquetImage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BouquetId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<short>("Position")
                        .HasColumnType("smallint");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("BouquetId");

                    b.ToTable("BouquetImages", null, t =>
                        {
                            t.HasCheckConstraint("CK_BouquetImage_Position", "\"Position\" BETWEEN 1 AND 3");
                        });
                });

            modelBuilder.Entity("CatalogService.Domain.Entities.BouquetRecipient", b =>
                {
                    b.Property<Guid>("BouquetId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RecipientId")
                        .HasColumnType("uuid");

                    b.HasKey("BouquetId", "RecipientId");

                    b.HasIndex("RecipientId");

                    b.ToTable("BouquetRecipients", (string)null);
                });

            modelBuilder.Entity("CatalogService.Domain.Entities.BouquetSize", b =>
                {
                    b.Property<Guid>("BouquetId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SizeId")
                        .HasColumnType("uuid");

                    b.HasKey("BouquetId", "SizeId");

                    b.HasIndex("SizeId");

                    b.ToTable("BouquetSizes", (string)null);
                });

            modelBuilder.Entity("CatalogService.Domain.Entities.Event", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Events", (string)null);
                });

            modelBuilder.Entity("CatalogService.Domain.Entities.Flower", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Quantity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Flowers", null, t =>
                        {
                            t.HasCheckConstraint("CK_Flower_Quantity_Positive", "\"Quantity\" >= 0");
                        });
                });

            modelBuilder.Entity("CatalogService.Domain.Entities.Recipient", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Recipients", (string)null);
                });

            modelBuilder.Entity("CatalogService.Domain.Entities.Size", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Sizes", (string)null);
                });

            modelBuilder.Entity("CatalogService.Domain.Entities.BouquetEvent", b =>
                {
                    b.HasOne("CatalogService.Domain.Entities.Bouquet", "Bouquet")
                        .WithMany("BouquetEvents")
                        .HasForeignKey("BouquetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CatalogService.Domain.Entities.Event", "Event")
                        .WithMany("BouquetEvents")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bouquet");

                    b.Navigation("Event");
                });

            modelBuilder.Entity("CatalogService.Domain.Entities.BouquetFlower", b =>
                {
                    b.HasOne("CatalogService.Domain.Entities.Bouquet", "Bouquet")
                        .WithMany("BouquetFlowers")
                        .HasForeignKey("BouquetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CatalogService.Domain.Entities.Flower", "Flower")
                        .WithMany("BouquetFlowers")
                        .HasForeignKey("FlowerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bouquet");

                    b.Navigation("Flower");
                });

            modelBuilder.Entity("CatalogService.Domain.Entities.BouquetImage", b =>
                {
                    b.HasOne("CatalogService.Domain.Entities.Bouquet", "Bouquet")
                        .WithMany("BouquetImages")
                        .HasForeignKey("BouquetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bouquet");
                });

            modelBuilder.Entity("CatalogService.Domain.Entities.BouquetRecipient", b =>
                {
                    b.HasOne("CatalogService.Domain.Entities.Bouquet", "Bouquet")
                        .WithMany("BouquetRecipients")
                        .HasForeignKey("BouquetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CatalogService.Domain.Entities.Recipient", "Recipient")
                        .WithMany("BouquetRecipients")
                        .HasForeignKey("RecipientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bouquet");

                    b.Navigation("Recipient");
                });

            modelBuilder.Entity("CatalogService.Domain.Entities.BouquetSize", b =>
                {
                    b.HasOne("CatalogService.Domain.Entities.Bouquet", "Bouquet")
                        .WithMany("BouquetSizes")
                        .HasForeignKey("BouquetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CatalogService.Domain.Entities.Size", "Size")
                        .WithMany("BouquetSizes")
                        .HasForeignKey("SizeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bouquet");

                    b.Navigation("Size");
                });

            modelBuilder.Entity("CatalogService.Domain.Entities.Bouquet", b =>
                {
                    b.Navigation("BouquetEvents");

                    b.Navigation("BouquetFlowers");

                    b.Navigation("BouquetImages");

                    b.Navigation("BouquetRecipients");

                    b.Navigation("BouquetSizes");
                });

            modelBuilder.Entity("CatalogService.Domain.Entities.Event", b =>
                {
                    b.Navigation("BouquetEvents");
                });

            modelBuilder.Entity("CatalogService.Domain.Entities.Flower", b =>
                {
                    b.Navigation("BouquetFlowers");
                });

            modelBuilder.Entity("CatalogService.Domain.Entities.Recipient", b =>
                {
                    b.Navigation("BouquetRecipients");
                });

            modelBuilder.Entity("CatalogService.Domain.Entities.Size", b =>
                {
                    b.Navigation("BouquetSizes");
                });
#pragma warning restore 612, 618
        }
    }
}
